return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "actionlint",
      "ansible-language-server",
      "ansible-lint",
      "antlers-language-server",
      "stylua",
      "shfmt",
      "vue-language-server",
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "intelephense",
      "nginx-language-server",
      "php-debug-adapter",
      "php-cs-fixer",
      "phpstan",
      "tailwindcss-language-server",
      "rustywind",
      "proselint",
      "write-good",
      "alex",
    },
  },
}
